### ISSUE TITLE
Error running docker-compose up on Win11

### ISSUE THREAD

**Issue by Ease78** [lazarst96/semantic-search#1]
=> ERROR [ 7/12] RUN python -m spacy download en_core_web_sm                                                                                                                                                                           1.1s
------
 > [ 7/12] RUN python -m spacy download en_core_web_sm:
#11 0.992 Traceback (most recent call last):
#11 0.992   File "__init__.pxd", line 942, in numpy.import_array
#11 0.992 RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
#11 0.992
#11 0.992 During handling of the above exception, another exception occurred:
#11 0.992
#11 0.992 Traceback (most recent call last):
#11 0.992   File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
#11 0.992     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
#11 0.992   File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
#11 0.992     return _get_module_details(pkg_main_name, error)
#11 0.992   File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
#11 0.992     __import__(pkg_name)
#11 0.992   File "/usr/local/lib/python3.8/site-packages/spacy/__init__.py", line 14, in <module>
#11 0.992     from . import pipeline  # noqa: F401
#11 0.992   File "/usr/local/lib/python3.8/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
#11 0.992     from .attributeruler import AttributeRuler
#11 0.992   File "/usr/local/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
#11 0.992     from .pipe import Pipe
#11 0.992   File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
#11 0.993   File "spacy/vocab.pyx", line 1, in init spacy.vocab
#11 0.993   File "spacy/lexeme.pyx", line 6, in init spacy.lexeme
#11 0.993   File "__init__.pxd", line 944, in numpy.import_array
#11 0.993 ImportError: numpy.core.multiarray failed to import
------
executor failed running [/bin/sh -c python -m spacy download en_core_web_sm]: exit code: 1
ERROR: Service 'search-api' failed to build : Build failed

**Comment by Ease78** [comment]
I changed the Numpy version to the latest available one and the installation finished but it didn't start.

Starting semantic-search-main_tf-serving_1 ... error

ERROR: for semantic-search-main_tf-serving_1  Cannot start service tf-serving: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown

ERROR: for tf-serving  Cannot start service tf-serving: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by Ease78** [comment]
I was able to resolve the previous issue by adding the config file from Milvus server https://milvus.io/docs/v1.0.0/milvus_config.md
